research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2025.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
  output_file: research.md

gist_task:
  description: >
    Review the context you got and compress it into 5 minute gist, keeping only important details.
    Make sure the gist contains all relevant information and makes the reader want to read full research.
  expected_output: >
    5 minute gist for high-level decision makers. Formatted as markdown without '```'
  agent: writer
  output_file: gist.md
